version: '3'
services:  # Используемые сервисы
  php: # Директива имени контейнера
    build: 
      context: ./docker/php # Путь к dockerfile который отвечает за сборку
    volumes: # Директива для записи файла index.php в контейнер
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80 # Порт local:container
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d' # Путь к базовым настройкам сервера local:container

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root # Добавили пароль для бд
    volumes:
      - './docker/volume/mysql:/var/lib/mysql' # 








